name: test

on: [push]

jobs:
  test:

    strategy:
      matrix:
        go-version: [1.16.x]
        os: ["${{ vars.ACTIONS_RUNNER }}", macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
    
    - name: Setup
      uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492 # v2
      with:
        go-version: ${{ matrix.go-version }}
    
    - name: Dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint
        
    - name: Build
      run: make build
      
    - name: Code Style
      run: make lint
    
    - name: Test PR
      if: github.ref != 'refs/heads/master'
      run: make test

    - name: Test Master
      if: github.ref == 'refs/heads/master'
      env:
          UPCLOUD_API_USER: ${{ secrets.UPCLOUD_API_USER }}
          UPCLOUD_API_PASSWORD: ${{ secrets.UPCLOUD_API_PASSWORD }}
          PACKER_ACC: 1
      run: make test_integration
